const express = require('express');
const router = express.Router();

// Demo agents for public testing
const demoAgents = {
    'content-generator': {
        name: 'Content Generator',
        description: 'Generates creative content based on your input'
    },
    'code-assistant': {
        name: 'Code Assistant',
        description: 'Helps with code generation and debugging'
    },
    'customer-support': {
        name: 'Customer Support Bot',
        description: 'Provides automated customer support responses'
    },
    'data-analyzer': {
        name: 'Data Analyzer',
        description: 'Analyzes data and provides insights'
    }
};

// Execute demo (public endpoint with rate limiting)
router.post('/execute', async (req, res) => {
    try {
        const { agentId, input } = req.body;
        
        if (!agentId || !input) {
            return res.status(400).json({ error: 'Agent ID and input are required' });
        }
        
        const agent = demoAgents[agentId];
        
        if (!agent) {
            return res.status(404).json({ error: 'Demo agent not found' });
        }
        
        // Simulate processing delay
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        // Generate demo response based on agent type
        let output;
        switch (agentId) {
            case 'content-generator':
                output = `🎨 Content Generated:\n\nTitle: ${input}\n\nThis is a sample blog post introduction about "${input}". In a production environment, this would be generated by an AI model that creates engaging, creative content tailored to your specifications.\n\n[Rest of the article would continue here...]`;
                break;
            case 'code-assistant':
                output = `💻 Code Solution:\n\n\`\`\`javascript\n// Solution for: ${input}\n\nfunction solution() {\n  // This is a demo response\n  // In production, this would provide actual code\n  console.log("Processing: ${input}");\n  return "Demo implementation";\n}\n\nsolution();\n\`\`\`\n\nThis is a simulated code response. The production version would analyze your request and generate appropriate code.`;
                break;
            case 'customer-support':
                output = `🤝 Support Response:\n\nThank you for contacting us about: "${input}"\n\nI understand your concern. Here's what I can help you with:\n\n1. Immediate assistance with your query\n2. Step-by-step guidance\n3. Additional resources if needed\n\nIs there anything specific you'd like me to clarify?\n\n[In production, this would use NLP to understand and respond to customer queries accurately]`;
                break;
            case 'data-analyzer':
                output = `📊 Analysis Results:\n\nAnalyzing: ${input}\n\n**Key Insights:**\n- Trend: Positive growth pattern detected\n- Confidence: 85%\n- Recommendation: Continue monitoring\n\n**Summary:**\nThis demo shows how the data analyzer would process your input. In production, this would perform actual data analysis using advanced algorithms.\n\n[Detailed analysis would follow...]`;
                break;
            default:
                output = `Demo response for: ${input}`;
        }
        
        res.json({
            agentId,
            agentName: agent.name,
            input,
            output,
            executedAt: new Date().toISOString(),
            isDemo: true
        });
    } catch (error) {
        console.error('Demo execution error:', error);
        res.status(500).json({ error: 'Demo execution failed' });
    }
});

// Get available demo agents
router.get('/agents', (req, res) => {
    res.json({
        agents: Object.entries(demoAgents).map(([id, agent]) => ({
            id,
            ...agent
        }))
    });
});

module.exports = router;
